# Generated by Django 5.1.7 on 2025-11-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sitesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='enable_about_us_page',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='enable_directory_page',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='enable_news_page',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='enable_service_page',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='enable_sponsor_us_page',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_about_sis_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_check_turnitin_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_criteria_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_directory_researchers_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_indexed_articles_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_indexed_journals_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_landing_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_mission_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_powerpoint_preparation_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_project_archive_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_service_solution_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_sponsors_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_thesis_to_article_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_thesis_to_book_chapter_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_thesis_to_book_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_tolerance_policy_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_work_plagiarism_page',
            field=models.BooleanField(default=True),
        ),
    ]
