# Generated by Django 5.1.7 on 2025-11-15 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_sitesettings_enable_about_us_page_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('category', models.CharField(choices=[('opinion', 'Opinion'), ('technology', 'Technology'), ('medicine_health', 'Medicine and Health'), ('education', 'Education'), ('science', 'Science'), ('business', 'Business'), ('general', 'General')], default='general', max_length=50)),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('order_priority', models.IntegerField(default=5, help_text='On a scale of 1 to 9')),
                ('views', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_date', '-order_priority'],
            },
        ),
    ]
