# Generated by Django 5.1.7 on 2025-11-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='carousel_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='settings/carousel/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='carousel_image_1_subtitle',
            field=models.TextField(blank=True, default='Explore groundbreaking research papers, cutting-edge methodologies, and innovative findings that shape the future of knowledge and discovery.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='carousel_image_1_title',
            field=models.CharField(blank=True, default='Advancing Research Through Innovation', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='carousel_image_1_url',
            field=models.URLField(blank=True, help_text='Alternative: Provide image URL instead of uploading'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='carousel_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='settings/carousel/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='carousel_image_2_subtitle',
            field=models.TextField(blank=True, default='Explore groundbreaking research papers, cutting-edge methodologies, and innovative findings that shape the future of knowledge and discovery.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='carousel_image_2_title',
            field=models.CharField(blank=True, default='Advancing Research Through Innovation', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='carousel_image_2_url',
            field=models.URLField(blank=True, help_text='Alternative: Provide image URL instead of uploading'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='carousel_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='settings/carousel/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='carousel_image_3_subtitle',
            field=models.TextField(blank=True, default='Explore groundbreaking research papers, cutting-edge methodologies, and innovative findings that shape the future of knowledge and discovery.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='carousel_image_3_title',
            field=models.CharField(blank=True, default='Advancing Research Through Innovation', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='carousel_image_3_url',
            field=models.URLField(blank=True, help_text='Alternative: Provide image URL instead of uploading'),
        ),
    ]
