# Generated by Django 5.1.7 on 2025-11-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_project_downloads_project_price_usd_project_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='journal_cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='journals/covers/'),
        ),
        migrations.AddField(
            model_name='journal',
            name='journal_format',
            field=models.CharField(blank=True, choices=[('print', 'Print'), ('online', 'Online'), ('both', 'Both Print and Online')], max_length=50),
        ),
        migrations.AddField(
            model_name='journal',
            name='journal_type',
            field=models.CharField(blank=True, choices=[('open-access', 'Open Access'), ('subscription', 'Subscription'), ('hybrid', 'Hybrid')], max_length=50),
        ),
        migrations.AddField(
            model_name='journal',
            name='journal_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='open_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journal',
            name='peer_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journal',
            name='publication_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
