# Generated by Django 5.1.7 on 2025-11-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_journal_journal_cover_image_journal_journal_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authors_names',
            field=models.CharField(blank=True, help_text='Comma-separated author names', max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='country_of_publication',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/covers/'),
        ),
        migrations.AddField(
            model_name='article',
            name='issue',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='journal_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='article',
            name='pages',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='volume',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='year_of_publication',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_type',
            field=models.CharField(blank=True, choices=[('open-access', 'Open-Access Journal'), ('subscription', 'Subscription-Based Journal'), ('hybrid', 'Hybrid'), ('trade', 'Trade Journal'), ('current-affairs', 'Current affairs/Opinion Magazine'), ('popular', 'Popular Magazine'), ('preprint', 'Pre-Print Journal')], max_length=50),
        ),
    ]
