# Generated by Django 5.1.7 on 2025-11-15 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_enable_sponsors_page_to_enable_donate_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiprequest',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='membership_requests/profiles/'),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='membership_requests/cvs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='membership_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('institutional', 'Institutional'), ('corporate', 'Corporate')], default='individual', max_length=50),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='motivation_letter',
            field=models.FileField(blank=True, null=True, upload_to='membership_requests/letters/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
