# Generated by Django 5.2.7 on 2025-11-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_membershiprequest_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plagiarismcheck',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plagiarismcheck',
            name='whatsapp_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plagiarismcheck',
            name='check_type',
            field=models.CharField(choices=[('standard', 'Standard Check'), ('comprehensive', 'Comprehensive Check'), ('quick', 'Quick Check')], default='standard', max_length=50),
        ),
        migrations.AlterField(
            model_name='plagiarismcheck',
            name='document_title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='plagiarismcheck',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
