# Generated by Django 5.2.7 on 2025-11-15 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_plagiarismcheck_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plagiarismwork',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='plagiarismwork',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='plagiarismwork',
            name='privacy_accepted',
        ),
        migrations.RemoveField(
            model_name='plagiarismwork',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='plagiarismwork',
            name='urgency',
        ),
        migrations.AddField(
            model_name='plagiarismwork',
            name='plagiarism_percentage',
            field=models.CharField(choices=[('0-10', '0-10%'), ('11-20', '11-20%'), ('21-30', '21-30%'), ('31-40', '31-40%'), ('41-50', '41-50%'), ('51-60', '51-60%'), ('61-70', '61-70%'), ('71-80', '71-80%'), ('81-90', '81-90%'), ('91-100', '91-100%')], default='0-10', max_length=20),
        ),
        migrations.AddField(
            model_name='plagiarismwork',
            name='plagiarism_report',
            field=models.FileField(blank=True, help_text='Plagiarism report in PDF format', null=True, upload_to='plagiarism_work/reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='plagiarismwork',
            name='submission_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='plagiarismwork',
            name='whatsapp_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plagiarismwork',
            name='document',
            field=models.FileField(help_text='MS Word file to work on', upload_to='plagiarism_work/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx'])]),
        ),
    ]
