# Generated by Django 5.2.7 on 2025-11-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_halloffameapplication_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesistoarticle',
            name='number_of_article',
            field=models.CharField(blank=True, help_text='Number of articles to be extracted (e.g., 3, 4, or 5)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='thesistoarticle',
            name='submission_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='thesistoarticle',
            name='whatsapp_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='thesistoarticle',
            name='article_type',
            field=models.CharField(choices=[('research-article', 'Research Article'), ('review-article', 'Review Article'), ('case-study', 'Case Study'), ('short-communication', 'Short Communication'), ('letter', 'Letter to Editor')], default='research-article', max_length=50),
        ),
    ]
