# Generated by Django 5.2.7 on 2025-11-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_thesistoarticle_number_of_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesistobook',
            name='number_of_books',
            field=models.CharField(blank=True, help_text='Number of books to be extracted (e.g., 3, 4, or 5)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='thesistobook',
            name='submission_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='thesistobook',
            name='whatsapp_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='thesistobook',
            name='book_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='thesistobook',
            name='book_type',
            field=models.CharField(blank=True, choices=[('monograph', 'Monograph'), ('textbook', 'Textbook'), ('edited-volume', 'Edited Volume'), ('reference-book', 'Reference Book')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='thesistobook',
            name='chapter_structure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thesistobook',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='thesistobook',
            name='special_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thesistobook',
            name='target_audience',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
