# Generated by Django 5.2.7 on 2025-11-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_thesistobook_number_of_books_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesistobookchapter',
            name='number_of_chapters',
            field=models.CharField(blank=True, help_text='Number of chapters to be extracted (e.g., 3, 4, or 5)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='thesistobookchapter',
            name='submission_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='thesistobookchapter',
            name='whatsapp_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='thesistobookchapter',
            name='chapter_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='thesistobookchapter',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='thesistobookchapter',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thesistobookchapter',
            name='target_book',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='thesistobookchapter',
            name='thesis_section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
