# Generated by Django 5.2.7 on 2025-11-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_thesistobookchapter_number_of_chapters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerpointpreparation',
            name='number_of_slides',
            field=models.CharField(blank=True, help_text='Number of PowerPoint slides (e.g., 10, 3, 44 or 53)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='powerpointpreparation',
            name='submission_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='powerpointpreparation',
            name='whatsapp_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='powerpointpreparation',
            name='design_style',
            field=models.CharField(blank=True, choices=[('professional', 'Professional'), ('modern', 'Modern'), ('minimalist', 'Minimalist'), ('academic', 'Academic'), ('creative', 'Creative')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='powerpointpreparation',
            name='duration',
            field=models.CharField(blank=True, choices=[('10', '10 minutes'), ('15', '15 minutes'), ('20', '20 minutes'), ('30', '30 minutes'), ('45', '45 minutes'), ('60', '60 minutes')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='powerpointpreparation',
            name='include_acknowledgments',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='powerpointpreparation',
            name='include_conclusion',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='powerpointpreparation',
            name='include_discussion',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='powerpointpreparation',
            name='include_intro',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='powerpointpreparation',
            name='include_methodology',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='powerpointpreparation',
            name='include_objectives',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='powerpointpreparation',
            name='include_references',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='powerpointpreparation',
            name='include_results',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='powerpointpreparation',
            name='include_title',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='powerpointpreparation',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='powerpointpreparation',
            name='presentation_type',
            field=models.CharField(blank=True, choices=[('defense', 'Thesis Defense'), ('conference', 'Conference Presentation'), ('seminar', 'Seminar/Workshop'), ('academic', 'Academic Presentation'), ('general', 'General Presentation')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='powerpointpreparation',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
