from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.landing, name='landing'),
    path('browse/', views.browse, name='browse'),
    path('submit/', views.submit, name='submit'),
    path('about/', views.about, name='about'),
    path('auth/', views.auth, name='auth'),
    path('logout/', views.logout_view, name='logout'),
    path('indexed_articles/', views.indexed_articles, name='indexed_articles'),
    path('indexed_articles/view/<int:article_id>/', views.article_detail, name='article_detail'),
    path('indexed_articles/certificate/<int:article_id>/', views.article_certificate, name='article_certificate'),
    path('indexed_journals/', views.indexed_journals, name='indexed_journals'),
    path('indexed_journals/view/<int:journal_id>/', views.journal_detail, name='journal_detail'),
    path('project_archive/', views.project_archive, name='project_archive'),
    path('project_archive/view/<int:project_id>/', views.project_detail, name='project_detail'),
    path('project_archive/verify-payment/<int:project_id>/', views.verify_project_payment, name='verify_project_payment'),
    path('upload_article/', views.upload_article, name='upload_article'),
    path('register_journal/', views.register_journal, name='register_journal'),
    path('directory_researchers/', views.directory_researchers, name='directory_researchers'),
    path('upload_project/', views.upload_project, name='upload_project'),
    path('council_members/', views.council_members, name='council_members'),
    path('team_members/', views.team_members, name='team_members'),
    path('donate/', views.donate, name='donate'),
    path('sponsors/', views.sponsors, name='sponsors'),
    path('initialize-payment/', views.initialize_payment, name='initialize_payment'),
    path('request_membership/', views.request_membership, name='request_membership'),
    path('apply_directory/', views.apply_directory, name='apply_directory'),
    path('hall_of_fame/', views.hall_of_fame, name='hall_of_fame'),
    path('hall_of_fame/apply/', views.hall_of_fame_apply, name='hall_of_fame_apply'),
    path('check_turnitin/', views.check_turnitin, name='check_turnitin'),
    path('work_plagiarism/', views.work_plagiarism, name='work_plagiarism'),
    path('thesis_to_article/', views.thesis_to_article, name='thesis_to_article'),
    path('thesis_to_book/', views.thesis_to_book, name='thesis_to_book'),
    path('thesis_to_book_chapter/', views.thesis_to_book_chapter, name='thesis_to_book_chapter'),
    path('powerpoint_preparation/', views.powerpoint_preparation, name='powerpoint_preparation'),
    path('about_sis/', views.about_sis, name='about_sis'),
    path('mission/', views.mission, name='mission'),
    path('criteria/', views.criteria, name='criteria'),
    path('tolerance_policy/', views.tolerance_policy, name='tolerance_policy'),
    path('service_solution/', views.service_solution, name='service_solution'),
    path('policy_terms/', views.policy_terms, name='policy_terms'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('settings/', views.settings, name='settings'),
    path('account_detail/', views.account_detail, name='account_detail'),
    path('edit_account/', views.edit_account, name='edit_account'),
    path('view_account/<int:user_id>/', views.view_account, name='view_account'),
    path('list_accounts/', views.list_accounts, name='list_accounts'),
    path('get_user_data/<int:user_id>/', views.get_user_data, name='get_user_data'),
    path('edit_user_account/<int:user_id>/', views.edit_user_account, name='edit_user_account'),
    path('update_user_role/<int:user_id>/', views.update_user_role, name='update_user_role'),
    path('delete_user_account/<int:user_id>/', views.delete_user_account, name='delete_user_account'),
    path('export_account/<int:user_id>/<str:format_type>/', views.export_account, name='export_account'),
    path('change_email/', views.change_email, name='change_email'),
    path('reset_password/', views.reset_password, name='reset_password'),
    path('news/', views.news_list, name='news_list'),
    path('news/add/', views.news_add, name='news_add'),
    path('news/edit/<int:blog_id>/', views.news_edit, name='news_edit'),
    path('news/delete/<int:blog_id>/', views.news_delete, name='news_delete'),
    path('news/toggle-publish/<int:blog_id>/', views.news_toggle_publish, name='news_toggle_publish'),
]

