from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.landing, name='landing'),
    path('browse/', views.browse, name='browse'),
    path('submit/', views.submit, name='submit'),
    path('about/', views.about, name='about'),
    path('auth/', views.auth, name='auth'),
    path('indexed_articles/', views.indexed_articles, name='indexed_articles'),
    path('indexed_articles/view/<int:article_id>/', views.article_detail, name='article_detail'),
    path('indexed_journals/', views.indexed_journals, name='indexed_journals'),
    path('project_archive/', views.project_archive, name='project_archive'),
    path('upload_article/', views.upload_article, name='upload_article'),
    path('register_journal/', views.register_journal, name='register_journal'),
    path('directory_researchers/', views.directory_researchers, name='directory_researchers'),
    path('upload_project/', views.upload_project, name='upload_project'),
    path('council_members/', views.council_members, name='council_members'),
    path('team_members/', views.team_members, name='team_members'),
    path('sponsors/', views.sponsors, name='sponsors'),
    path('initialize-payment/', views.initialize_payment, name='initialize_payment'),
    path('request_membership/', views.request_membership, name='request_membership'),
    path('apply_directory/', views.apply_directory, name='apply_directory'),
    path('hall_of_fame/', views.hall_of_fame, name='hall_of_fame'),
    path('hall_of_fame/apply/', views.hall_of_fame_apply, name='hall_of_fame_apply'),
    path('check_turnitin/', views.check_turnitin, name='check_turnitin'),
    path('work_plagiarism/', views.work_plagiarism, name='work_plagiarism'),
    path('thesis_to_article/', views.thesis_to_article, name='thesis_to_article'),
    path('thesis_to_book/', views.thesis_to_book, name='thesis_to_book'),
    path('thesis_to_book_chapter/', views.thesis_to_book_chapter, name='thesis_to_book_chapter'),
    path('powerpoint_preparation/', views.powerpoint_preparation, name='powerpoint_preparation'),
    path('about_sis/', views.about_sis, name='about_sis'),
    path('mission/', views.mission, name='mission'),
    path('criteria/', views.criteria, name='criteria'),
    path('tolerance_policy/', views.tolerance_policy, name='tolerance_policy'),
    path('service_solution/', views.service_solution, name='service_solution'),
    path('policy_terms/', views.policy_terms, name='policy_terms'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('account_detail/', views.account_detail, name='account_detail'),
    path('edit_account/', views.edit_account, name='edit_account'),
    path('change_email/', views.change_email, name='change_email'),
    path('reset_password/', views.reset_password, name='reset_password'),
]

